#criar a imagem ubuntu
FROM ubuntu:bionic

RUN apt-get update \
  && apt-get install -y \
  bind9 \
  bind9utils \
  bind9-doc

# ativa o IPv4
RUN sed -i 's/OPTIONS=.*/OPTIONS="-4 -u bind"/' /etc/default/bind9

# copia os arquivos de configuraçao
COPY named.conf.options /etc/bind/
COPY named.conf.local /etc/bind/
COPY db.asa-teste.com /etc/bind/zones/

# vai ficar executando em um loop infinito
CMD ["/bin/bash", "-c", "while :; do sleep 10; done"]

